# Generated by Django 5.2.12 on 2026-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('lida', 'Lida')], default='enviada', max_length=10)),
            ],
        ),
    ]
