# Generated by Django 5.2.12 on 2026-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_created_at_user_user_type_alter_message_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
