# Generated by Django 5.2.12 on 2026-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, default='Novo Template', max_length=255),
        ),
    ]
