# Generated by Django 5.2.12 on 2026-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
