# Generated by Django 5.2.13 on 2026-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('Claro', 'Claro'), ('Escuro', 'Escuro')], default='Claro', max_length=10),
        ),
    ]
