# Generated by Django 5.2.13 on 2026-08-24 21:41
from django.db import migrations


def marcar_como_verificado(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(email_verified=False).update(email_verified=True)


def reverter(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_email_verified_user_verification_attempts_and_more'),
    ]

    operations = [
        migrations.RunPython(marcar_como_verificado, reverter),
    ]