# Generated by Django 5.2.13 on 2026-08-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_message_options_message_destinatario_and_more'),
        ('core', '0016_marcar_usuarios_existentes_verificados'),
    ]

    operations = [
    ]
