# Generated by Django 5.2.13 on 2026-10-03 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260827_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='desing',
            name='canvas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desing',
            name='em_andamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desing',
            name='foto_original',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='desing',
            name='importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desing',
            name='meu_projeto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='desing',
            name='miniatura',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='desing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='desing',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desings', to=settings.AUTH_USER_MODEL),
        ),
    ]
