# Generated by Django 5.2.13 on 2026-10-06 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260827_1714'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('login', 'Login')], max_length=20)),
                ('entity', models.CharField(choices=[('design', 'Design'), ('element', 'Elemento'), ('template', 'Template'), ('user', 'Usuário'), ('company', 'Empresa')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('field_name', models.CharField(blank=True, max_length=80, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Novo Design', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Texto'), ('title', 'Título'), ('image', 'Imagem'), ('shape', 'Forma')], max_length=45)),
                ('content', models.CharField(blank=True, max_length=250)),
                ('posicao_x', models.IntegerField()),
                ('posicao_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('heigth', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=20)),
                ('shape_type', models.CharField(blank=True, choices=[('rect', 'Retângulo'), ('circle', 'Círculo')], max_length=20, null=True)),
                ('stroke_width', models.IntegerField(blank=True, default=3, null=True)),
                ('layer_order', models.IntegerField(default=0)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['layer_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('family', models.CharField(max_length=80)),
                ('styles', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fontes',
            },
        ),
        migrations.CreateModel(
            name='TemplateAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acesso ao template',
                'verbose_name_plural': 'Acessos aos templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Texto'), ('title', 'Título'), ('image', 'Imagem'), ('shape', 'Forma')], max_length=45)),
                ('content', models.CharField(blank=True, max_length=250)),
                ('posicao_x', models.IntegerField()),
                ('posicao_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('heigth', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Elemento de template',
                'verbose_name_plural': 'Elementos de template',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('colors', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.DeleteModel(
            name='Desing',
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AddField(
            model_name='template',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='templates', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='design',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='core.template'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.design'),
        ),
        migrations.AddField(
            model_name='element',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='core.design'),
        ),
        migrations.AddField(
            model_name='template',
            name='fonts',
            field=models.ManyToManyField(blank=True, related_name='templates', to='core.font'),
        ),
        migrations.AddField(
            model_name='templateaccessgrant',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.template'),
        ),
        migrations.AddField(
            model_name='templateaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_elements', to='core.template'),
        ),
        migrations.AddField(
            model_name='design',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='core.theme'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['design', '-created_at'], name='core_auditl_design__1052b8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateaccessgrant',
            unique_together={('template', 'user')},
        ),
    ]
