# Generated by Django 5.2.13 on 2026-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auditlog_design_element_font_templateaccessgrant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
