# Generated by Django 5.2.13 on 2026-10-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_desing_canvas_desing_em_andamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desing',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
