# Generated by Django 5.2.13 on 2026-10-08 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_element_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='font_family',
            field=models.CharField(blank=True, default='Poppins', max_length=100),
        ),
        migrations.AddField(
            model_name='element',
            name='font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='font_style',
            field=models.CharField(blank=True, default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='element',
            name='font_weight',
            field=models.CharField(blank=True, default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='element',
            name='stroke_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='element',
            name='text_align',
            field=models.CharField(blank=True, default='left', max_length=30),
        ),
        migrations.AlterField(
            model_name='element',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='shape_type',
            field=models.CharField(blank=True, choices=[('rect', 'Retângulo'), ('circle', 'Círculo'), ('triangle', 'Triângulo'), ('star', 'Estrela')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='stroke_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
