# Generated by Django 5.2.13 on 2026-10-08 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_element_font_family_element_font_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Página 1', max_length=255)),
                ('page_order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1080)),
                ('height', models.PositiveIntegerField(default=1080)),
                ('background_color', models.CharField(blank=True, default='#FFFFFF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.design')),
            ],
            options={
                'ordering': ['page_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='element',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='core.designpage'),
        ),
        migrations.AddConstraint(
            model_name='designpage',
            constraint=models.UniqueConstraint(fields=('design', 'page_order'), name='unique_page_order_per_design'),
        ),
    ]
